# MySQL 配置
[mysql]
host = localhost
user = root
password = 123456
database = law_chain

# Redis 配置
[redis]
host = localhost
port = 6379
password = 1234
db = 0

# 日志配置
[logger]
log_file = app.log

# BM25 搜索配置
[bm25]
min_top = 22
min_gap = 5

# Milvus 配置
[milvus]
host = localhost
port = 19530
data_name = law_chain
collection_cases = law_cases
collection_articles = law_clause

# LLM 配置
[llm]
model = deepseek-flash
dashscope_base_url = https://api.deepseek.com

# 检索参数配置
[retrieval]
vector_dim = 1024
case_retrieval_k = 5
case_candidate_m = 3
clause_retrieval_k = 6
clause_candidate_m = 4


# 应用配置
[app]
phone = 123-456-7890

